### ISSUE TITLE
Is it a typo in the paper?

### ISSUE THREAD

**Issue by huangmozhilv** [adalca/neuron#2]
Hi Adrian, in the paper page 9292 equation (3), why the parameter theta is z given s as marked red in the screenshot? Isn't it theta x given s? Could you clarify it? Thank you.
![image](https://user-images.githubusercontent.com/26662685/47148376-27268a80-d303-11e8-8303-0b430791156a.png)

**Comment by adalca** [comment]
HI, Yes I believe this is a typo and you are correct!
