### ISSUE TITLE
Compatibility issue with recent TensorFlow versions

### ISSUE THREAD

**Issue by timroelofs123** [adalca/neuron#31]
I am currently using TensorFlow 2.4.1, and am getting an error related to the usage of tf.random_normal in the class SampleNormalLogVar(Layer), which has been deprecated since tf version 2.1.0 I believe, and is now replaced with tf.random.normal. I am not using neurite by itself, but VoxelMorph, which uses this class for its vxm_model when the use_probs parameters is set to True.

**Comment by adalca** [comment]
@timroelofs123 
Thanks for the note! 

This has actually been updated and you can see it in the `dev` branch. We'll make a new release and move the changes to the `master` branch at some point, but in the meanwhile you should just switch to the dev branch and hopefully that should work (let us know if not!)
