### ISSUE TITLE
 ImportError: cannot import name 'mean_absolute_error' from 'tensorflow.keras.losses' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/keras/_tf_keras/keras/losses/__init__.py)

### ISSUE THREAD

**Issue by dwang6524** [adalca/neuron#87]
Hi there, unsure if this is the right place to post this.

Just getting the following issue!

``
----> 6 import voxelmorph as vxm
      7 import neurite as ne

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/voxelmorph/__init__.py:12
      9 from packaging import version
     11 # ensure valid neurite version is available
---> 12 import neurite
     13 minv = '0.2'
     14 curv = getattr(neurite, '__version__', None)

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/neurite/__init__.py:50
     47 except ImportError:
     48     raise ImportError('Please install tensorflow to use this neurite backend')
---> 50 from . import tf
     51 from .tf import *

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/neurite/tf/__init__.py:5
      3 from . import generators
      4 from . import callbacks
----> 5 from . import metrics
      6 from . import losses
      7 from . import models

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/neurite/tf/metrics.py:33
     31 from tensorflow.keras import losses
     32 # simple metrics renamed mae -> l1, mse -> l2
---> 33 from tensorflow.keras.losses import mean_absolute_error as l1
     34 from tensorflow.keras.losses import mean_squared_error as l2
     36 # local

ImportError: cannot import name 'mean_absolute_error' from 'tensorflow.keras.losses' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/keras/_tf_keras/keras/losses/__init__.py)
``

**Comment by ZFD1** [comment]
i got same error

**Comment by ZFD1** [comment]
maybe should use tensorflow 1.x ?

**Comment by adalca** [comment]
hm, I tried this in collab and it all works. Maybe you can start debugging from there? see the versions at the end of the file:

https://colab.research.google.com/drive/17RsS8lfxfrscZS3GwsxgtPKzqFgN_KPO?usp=sharing

**Comment by adalca** [comment]
Also see this recent tensorflow issue: https://github.com/tensorflow/tensorflow/issues/69851

**Comment by ZFD1** [comment]
> hm, I tried this in collab and it all works. Maybe you can start debugging from there? see the versions at the end of the file:
> 
> https://colab.research.google.com/drive/17RsS8lfxfrscZS3GwsxgtPKzqFgN_KPO?usp=sharing

Thank you !  using you provide environment version, it working !
